//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int CartDetailID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> BookID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
